In [2]:
import numpy as np
X = np.array([[1,0,0],[1,1,1],[1,2,2],[1,3,3],[1,4,4],[1,5,5]])
X

array([[1, 0, 0],
       [1, 1, 1],
       [1, 2, 2],
       [1, 3, 3],
       [1, 4, 4],
       [1, 5, 5]])

In [26]:
h = np.array([1,1,8,1,1,1])
h

array([1, 1, 8, 1, 1, 1])

In [27]:
h.shape

(6,)

In [28]:
h = h.reshape((6,1))
h

array([[1],
       [1],
       [8],
       [1],
       [1],
       [1]])

In [29]:
h.shape

(6, 1)

In [30]:
X

array([[1, 0, 0],
       [1, 1, 1],
       [1, 2, 2],
       [1, 3, 3],
       [1, 4, 4],
       [1, 5, 5]])

In [31]:
h

array([[1],
       [1],
       [8],
       [1],
       [1],
       [1]])

In [32]:
X * h

array([[ 1,  0,  0],
       [ 1,  1,  1],
       [ 8, 16, 16],
       [ 1,  3,  3],
       [ 1,  4,  4],
       [ 1,  5,  5]])

In [36]:
h.T.dot(X)

array([[13, 29, 29]])

In [37]:
X

array([[1, 0, 0],
       [1, 1, 1],
       [1, 2, 2],
       [1, 3, 3],
       [1, 4, 4],
       [1, 5, 5]])

In [39]:
np.sum(X, axis=0)

array([ 6, 15, 15])

In [40]:
W = np.random.randn(3,1)

In [41]:
W

array([[-0.92340437],
       [ 1.23211646],
       [-0.6740998 ]])

In [44]:
W[0,]

array([-0.92340437])

In [50]:
h = 0.1
threshold = 0.5
p = h >= threshold

In [51]:
p

False

In [52]:
p + 0

0

In [53]:
p.astype('int')

AttributeError: 'bool' object has no attribute 'astype'